apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: gatus
  namespace: fleet-local
spec:
  helm:
    pollingInterval: 1m
    repo: https://twin.github.io/helm-charts
    chart: gatus
    valuesFiles:
      - values.yaml
    takeOwnership: true
  defaultNamespace: gatus