apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: gatus
  namespace: fleet-local
spec:
  helm:
    pollingInterval: 1m
    repo: https://twin.github.io/helm-charts
    chart: gatus
    takeOwnership: true
    values:
      env:
        GATUS_CONFIG_PATH: /config
      envFrom:
        - secretRef:
            name: gatus-secret
      extraVolumeMounts:
        - name: gatus-config
          mountPath: /config/
          readOnly: true
          existingConfigMap: gatus
      config:
        endpoints: []
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: cert-issuer
        extraPaths: []
        hosts:
          - uptime.ryzen.me
        labels: {}
        path: /
        pathType: Prefix
        tls:
          - hosts:
            - uptime.ryzen.me
            secretName: gatus-tls
  defaultNamespace: gatus