apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: gatus
  namespace: gatus
spec:
  helm:
    pollingInterval: 1m
    repo: https://twin.github.io/helm-charts
    chart: gatus
    valuesFiles:
      - gatus/values.yaml
    valuesFrom:
      - secretKeyRef:
          name: gatus-secret
  targetNamespace: gatus