apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: keel
  namespace: kube-system
spec:
  chart: keel
  repo: https://charts.keel.sh
  targetNamespace: kube-system
  valuesContent: |-
    image:
      tag: latest
