apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart: nextcloud
  repo: https://nextcloud.github.io/helm/
  targetNamespace: nextcloud
  createNamespace: true
  valuesContent: |-
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cert-issuer
      hosts:
        - host: cal.ryzen.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: nextcloud-tls
          hosts:
            - cal.ryzen.me
    nextcloud:
      host: cal.ryzen.me
      extraEnv:
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: nextcloud-oidc-secret
              key: CLIENT_SECRET
        - name: OVERWRITEPROTOCOL
          value: https
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-postgresql-app
        usernameKey: username
        passwordKey: password
        hostKey: host
        databaseKey: dbname
    externalRedis:
      enabled: true
      host: nextcloud-redis-valkey
    metrics:
      enabled: true
    cronjob:
      enabled: true
    persistence:
      enabled: true
      storageClass: retain
    lifecycle:
      postStart:
        exec:
          command:
            - /bin/bash
            - -c
            - |
              for i in {1..20}; do
                if [ -f /var/www/html/config/config.php ]; then
                  break
                fi
                sleep 5
              done
              
              php occ config:system:set allow_local_remote_servers --value=true --type=bool || true
              
              php occ app:install user_oidc --keep-disabled --no-interaction || true
              php occ app:enable user_oidc || true
              
              php occ user_oidc:provider keycloak \
                --clientid="nextcloud" \
                --clientsecret="$OIDC_CLIENT_SECRET" \
                --discoveryuri="https://auth.ryzen.me/realms/public/.well-known/openid-configuration" || true
              
              php occ config:app:set --type=string --value=0 user_oidc allow_multiple_user_backends || true
