apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: signoz
  namespace: fleet-local
spec:
  helm:
    pollingInterval: 1m
    repo: https://charts.signoz.io
    chart: signoz
    values:
      signoz:
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: cert-issuer
          hosts:
            - host: signoz.ryzen.me
              paths:
                - path: /
                  pathType: ImplementationSpecific
                  port: 8080
          tls: 
          - secretName: signoz-tls
            hosts:
              - signoz.ryzen.me
        persistence:
          size: 5Gi
  defaultNamespace: monitoring