apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: harbor
spec:
  dnsNames:
    - harbor.ryzen.me
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer
  secretName: harbor-tls