apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: outline
  namespace: fleet-local
spec:
  helm:
    pollingInterval: 1m
    repo: https://gitlab.com/api/v4/projects/30221184/packages/helm/stable/
    chart: outline
    valuesFrom:
      - secretKeyRef:
          name: outline-secret
    values:
      env:
        SMTP_HOST: "ryzen.me"
        SMTP_PORT: "25"
        SMTP_USERNAME: "ryzen"
        SMTP_FROM_EMAIL: "outline@ryzen.me"
        SMTP_REPLY_EMAIL: "outline@ryzen.me"
        SMTP_SECURE: "false"
      postgresql:
        persistence:
          size: 6Gi
      minio:
        persistence:
          size: 30Gi
      ingress:
        host: outline.ryzen.me
        tls:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: cert-issuer
      redis:
        persistence:
          size: 3Gi
          secretKey:
    utilsSecret: {{ randAlphaNum 32 | b64enc | quote }}
    postgresql:
      postgresqlPassword: {{ randAlphaNum 32 | b64enc | quote }}
      postgresqlPostgresPassword: {{ randAlphaNum 32 | b64enc | quote }}
    minio:
      secretKey:
        password: {{ randAlphaNum 32 | b64enc | quote }}
      accessKey:
        password: {{ randAlphaNum 32 | b64enc | quote }}
  defaultNamespace: outline