apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: mailu
  namespace: fleet-local
spec:
  helm:
    pollingInterval: 1m
    repo: https://mailu.github.io/helm-charts/
    chart: mailu
    valuesFrom:
      - secretKeyRef:
          name: mailu-secret
    values:
      hostnames:
        - mail.ryzen.me
      domain: ryzen.me
      timezone: Etc/UTC
      externalDatabase:
        enabled: true
        type: postgresql
        host: mailu-postgresql-rw
        existingSecret: mailu-postgresql-app
        existingSecretDatabaseKey: dbname
      persistence:
        size: 20Gi
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: cert-issuer
  defaultNamespace: mailu