apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mailu-postgresql
  namespace: mailu
spec:
  instances: 3
  storage:
    size: 5Gi
    storageClass: retain
  bootstrap:
    initdb:
      database: mailu
      owner: mailu