apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
spec:
  acme:
    email: ryzen@ryzen.me
    profile: tlsserver
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-issuer-secret
    solvers:
    - http01:
        ingress:
          ingressClassName: traefik